# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F1vNTAv6v1BO22bQc18Hq9F6gRKiLsCG
"""

!pip install --upgrade reportlab

!pip install flask-ngrok

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip

!./ngrok authtoken 2YjWHtNSWb91xteJj95kIiV2bqV_337UTBzx5uQpyRjitUsME

from flask import Flask, render_template, request, jsonify
from tensorflow.keras.models import load_model
from reportlab.pdfgen import canvas
import datetime
from google.colab import files
from flask_ngrok import run_with_ngrok  # Import run_with_ngrok

# Loading the model
model = load_model('my_model.keras')

# Creating the Flask application
app = Flask(__name__)
run_with_ngrok(app)  # Initialize ngrok when the app is run

# Defining the route to handle GET requests (home page)
@app.route('/')
def home():
    return render_template('index.html')  # Adjust the name according to your initial template

# Define the route to handle POST requests (prediction)
@app.route('/predict', methods=['POST'])
def predict():
    # Get data from the request
    data = request.form['input_text']  # Adjust based on how you get data from the form

    # Make a prediction
    prediction = model.predict([data])[0]

    # Render the template with the prediction
    return render_template('result.html', prediction=prediction)

# Replacing with your own values
my_name = 'Jorge Alberto Jaramillo Bermudez'
batch_code = 'LISUM27'
submitted_to = 'Data Glacier'

# Creating a PDF document for Colab
pdf_path_colab = '/content/deployment_steps_colab.pdf'
pdf_colab = canvas.Canvas(pdf_path_colab)
pdf_colab.drawString(10, 800, f'Name: {my_name}')
pdf_colab.drawString(10, 780, f'Batch code: {batch_code}')
pdf_colab.drawString(10, 760, f'Submission date: {datetime.datetime.now()}')
pdf_colab.drawString(10, 740, f'Submitted to: {submitted_to}')
pdf_colab.save()

# Create another PDF document for local download
pdf_local_path = '/content/deployment_steps_local.pdf'
pdf_local = canvas.Canvas(pdf_local_path)
pdf_local.drawString(10, 800, f'Name: {my_name}')
pdf_local.drawString(10, 780, f'Batch code: {batch_code}')
pdf_local.drawString(10, 760, f'Submission date: {datetime.datetime.now()}')
pdf_local.drawString(10, 740, f'Submitted to: {submitted_to}')
pdf_local.save()

# Start the Flask application
if __name__ == '__main__':
    app.run()  # No use_reloader or debug when using ngrok

!./ngrok http 5000